[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Yevgnen Koh", email = "wherejoystarts@gmail.com"},
]
dependencies = [
    "requests>=2.28.2",
    "lxml>=4.9.2",
    "tqdm>=4.65.0",
    "filefox>=0.5.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
